# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1422eda668e5d7c2e34fefa33e8f3d53d4de125aaf2a634ab9c0004f05db61aeabe65f4d68999f7b15f1acecbe6d8de1cc9ae336a02bb89d02c1067980be409

test:
  secret_key_base: c1a86831ac77650af4754c8c7cca2f5d589ae5dae91d2c3b7e042ed2d344abfb8b1c75a613dbd06e5ad748d2148dd3a63ee19bacdce8ff0c6eb2e2b7f0a07fb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
